version: "3.9"

services:
  elite-tickets-db:
    container_name: elite-tickets-db
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    ports:
      - 5432:5432

  elite-tickets-mail:
    container_name: elite-tickets-mail
    image: bytemark/smtp
    expose:
      - 25
    ports:
      - "25:25"