version: "3.9"

services:
  elite-tickets-app:
    container_name: elite-tickets-app
    image: elite-tickets-app
    ports:
      - 8080:8080
    depends_on:
      - elite-tickets-db
      - elite-tickets-redis

  elite-tickets-db:
    container_name: elite-tickets-db
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elite_tickets_db
    ports:
      - 5432:5432

  elite-tickets-redis:
    container_name: elite-ticket-redis
    image: redis
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  elite-tickets-mail:
    container_name: elite-tickets-mail
    image: bytemark/smtp
    ports:
      - "25:25"
