version: "3.9"

services:
  elite-tickets-db:
    container_name: elite-tickets-db
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=elite_tickets_db
    expose:
      - 5432
    ports:
      - 5432:5432
