FROM maven:3.8.2-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests


FROM eclipse-temurin
WORKDIR /app
COPY --from=build /app/target/*.jar ./app.jar
EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
